[package]
name = "samp-codegen"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "0.4", features = ["nightly"] }
syn = { version = "0.15", features = ["full", "fold"] }
quote = "0.6"